services:
  app:
    build:
      context: ./
      dockerfile: Containerfile
      args:
        - E2E=true
    image: test
    environment:
      - DATABASE_URL=mongodb://root:root@db/admin
      - SESSION_SECRET=secret
    ports:
      - 8000:8000
    container_name: test

  db:
    image: docker.io/mongo:7.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    container_name: test_db

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    container_name: test_redis
