name: CI Client

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd Client/ && npm i && cd ../Server/ && npm i && cd ..
      - name: Check style
        run: cd Client/ && npm run lint . && cd ../Server/ && npm run lint . && cd ..
