name: Test, build and deploy to staging

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.1

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: |
          npm run test-all
        env:
          TEST_MONGODB_URI: "mongodb://localhost/test"
          PUBLIC_S3_ENDPOINT: ${{ secrets.UPCLOUD_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.UPCLOUD_BUCKET }}
          BUCKET_REGION: ${{ secrets.UPCLOUD_REGION }}
          ACCESS_KEY: ${{ secrets.UPCLOUD_ACCESS_KEY }}
          SECRET_ACCESS_KEY: ${{ secrets.UPCLOUD_SECRET_KEY }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
          SECRET: ${{ secrets.SECRET }}

      - name: Upload frontend & backend coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/frontend/lcov.info,coverage/backend/lcov.info

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and tag image
        id: build-image
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
        run: |
          docker build \
            --build-arg VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
            --build-arg VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
            --build-arg VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
            --build-arg VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
            -t 'quay.io/muvico_hy/muvico:staging' .

      - name: Push image to Quay.io
        id: push-to-quay
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          QUAY_IO_TOKEN: ${{ secrets.QUAY_IO_TOKEN }}
        run: |
          echo $QUAY_IO_TOKEN | docker login quay.io -u muvico_hy+robo --password-stdin
          docker push quay.io/muvico_hy/muvico:staging
